{% set version = "1.0.35" %}

{% set wabt_exes = [
    "spectest-interp",
    "wasm-decompile",
    "wasm-interp",
    "wasm-objdump",
    "wasm-stats",
    "wasm-strip",
    "wasm-validate",
    "wasm2c",
    "wasm2wat",
    "wast2json",
    "wat-desugar",
    "wat2wasm",
] %}

package:
  name: wabt
  version: {{ version }}

source:
  url: https://github.com/WebAssembly/wabt/releases/download/{{ version }}/wabt-{{ version }}.tar.xz
  sha256: 87210f895044137c01a588e9f5b4d1b0ed143c8c666440d387a0b7d2c5eff012

build:
  number: 0

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - cmake
    - ninja
    - python
  host:
    - openssl
  run:

test:
  commands:
    {% for exe in wabt_exes %}
    - which {{ exe }}   # [unix]
    - where {{ exe }}   # [win]
    - {{ exe }} --help  # [build_platform == target_platform]
    {% endfor %}

about:
  home: https://github.com/WebAssembly/wabt
  license: Apache-2.0
  license_file: LICENSE
  summary: The WebAssembly Binary Toolkit

extra:
  recipe-maintainers:
    - jakirkham
