travis:
  secure:
    BINSTAR_TOKEN: MVeRjE7NeOChokPSiKWh9FZowBA13ywobnkDJqaEOa5X95T8JaFq9bLlh9YGNaIfaayh+mOj2EisqcA0r2Gv1CaIQ1YHINQauY2R11YXEsbBe1rnRfVWOVLr8WmgZfMUG9vzTodsIcea7WcZV/v2mNL/AvkM9/FMqHC2yJekXpGu0cq3tQr2eIz926SgnaDOYQYLHLcswmu54T4BE/CDox4JJZDb7LjrCYRZBp61nAA5pOCE0pJQVbp4lGd2tsMA/erCediJHHUljUQvsnNiYiz6Pp8nBtbJTpo2W2f09lib4ktakX79lufAMhUdjbIuVIldT8q85cyza/Syxv87CMfNfA4fRuRy+3m7hTUz2X+Uj8K9MnaHVcyGGV6SbSMLykMJdG+3G42bODGJLnSvOhRCxrEYvo0clhhZ9CaDQ5QZQ2wRpHErxKr/ZQBEnVFFJU1S4CLnbby8lLyW47WrM051ZVgiEA68na+reLbKRcXwdCE5Nipr7wVi3wDKAfhP2XRJmkX/p85EYhmwVQ+Fka3xH5fNCMdZ5eRF3FW3yuivzy3VpgsGJIbimZr+kUcAwZSegrK5M+3P6guK352/l8Mwn2/ojqg9iIN+iX+EkhtXvVerz94JD6J0Vl8cxjgZ/aeg88/vs9jxo5632TGn1xTH9PKppaXzPtG0UjypCR0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
